# -*- coding: utf-8 -*-
# GENERADO automáticamente por pysap.codegen desde el PDF de la API.
# NO EDITAR A MANO: los cambios se perderán al regenerar.

from typing import Any
from pysap.objects.base import GuiComponent


class GuiComboBox(GuiComponent):
    @property
    def char_height(self) -> int: ...
    @property
    def char_left(self) -> int: ...
    @property
    def char_top(self) -> int: ...
    @property
    def char_width(self) -> int: ...
    @property
    def cur_list_box_entry(self) -> Any: ...
    @property
    def flushing(self) -> bool: ...
    @property
    def highlighted(self) -> bool: ...
    @property
    def is_left_label(self) -> bool: ...
    @property
    def is_list_box_active(self) -> bool: ...
    @property
    def is_right_label(self) -> bool: ...
    @property
    def key(self) -> str: ...
    @property
    def modified(self) -> bool: ...
    @modified.setter
    def modified(self, value: bool) -> None: ...
    @property
    def required(self) -> bool: ...
    @property
    def right_label(self) -> Any: ...
    @property
    def show_key(self) -> bool: ...
    @property
    def value(self) -> str: ...
    @value.setter
    def value(self, value: str) -> None: ...
    def set_key_space(self) -> None: ...
