# -*- coding: utf-8 -*-
# GENERADO automáticamente por pysap.codegen desde el PDF de la API.
# NO EDITAR A MANO: los cambios se perderán al regenerar.

from pysap.objects.base import GuiComponent


class GuiMainWindow(GuiComponent):
    @property
    def buttonbar_visible(self) -> bool: ...
    @buttonbar_visible.setter
    def buttonbar_visible(self, value: bool) -> None: ...
    @property
    def statusbar_visible(self) -> bool: ...
    @statusbar_visible.setter
    def statusbar_visible(self, value: bool) -> None: ...
    @property
    def titlebar_visible(self) -> bool: ...
    @titlebar_visible.setter
    def titlebar_visible(self, value: bool) -> None: ...
    @property
    def toolbar_visible(self) -> bool: ...
    @toolbar_visible.setter
    def toolbar_visible(self, value: bool) -> None: ...
    def resize_working_pane(self, width: int, height: int, throw_on_fail: bool) -> None: ...
    def resize_working_pane_ex(self, width: int, height: int, throw_on_fail: bool) -> None: ...
    def by_val(self) -> None: ...
    def the(self) -> None: ...
