# -*- coding: utf-8 -*-
# GENERADO automáticamente por pysap.codegen desde el PDF de la API.
# NO EDITAR A MANO: los cambios se perderán al regenerar.

from typing import Any
from pysap.objects.base import GuiComponent


class GuiGridView(GuiComponent):
    @property
    def column_count(self) -> int: ...
    @property
    def column_order(self) -> Any: ...
    @column_order.setter
    def column_order(self, value: Any) -> None: ...
    @property
    def current_cell_column(self) -> str: ...
    @current_cell_column.setter
    def current_cell_column(self, value: str) -> None: ...
    @property
    def current_cell_row(self) -> int: ...
    @current_cell_row.setter
    def current_cell_row(self, value: int) -> None: ...
    @property
    def first_visible_column(self) -> str: ...
    @first_visible_column.setter
    def first_visible_column(self, value: str) -> None: ...
    @property
    def first_visible_row(self) -> int: ...
    @first_visible_row.setter
    def first_visible_row(self, value: int) -> None: ...
    @property
    def frozen_column_count(self) -> int: ...
    @property
    def row_count(self) -> int: ...
    @property
    def selected_cells(self) -> Any: ...
    @selected_cells.setter
    def selected_cells(self, value: Any) -> None: ...
    @property
    def selected_columns(self) -> Any: ...
    @selected_columns.setter
    def selected_columns(self, value: Any) -> None: ...
    @property
    def selected_rows(self) -> str: ...
    @selected_rows.setter
    def selected_rows(self, value: str) -> None: ...
    @property
    def selection_mode(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def toolbar_button_count(self) -> int: ...
    @property
    def visible_row_count(self) -> int: ...
    def clear_selection(self) -> None: ...
    def click(self, row: int, column: str) -> None: ...
    def click_current_cell(self) -> None: ...
    def context_menu(self) -> None: ...
    def current_cell_moved(self) -> None: ...
    def delete_rows(self, rows: str) -> None: ...
    def deselect_column(self, column: str) -> None: ...
    def double_click(self, row: int, column: str) -> None: ...
    def double_click_current_cell(self) -> None: ...
    def duplicate_rows(self, rows: str) -> None: ...
    def get_cell_changeable(self, row: int, column: str) -> bool: ...
    def get_cell_check_box_checked(self, row: int, column: str) -> bool: ...
    def get_cell_color(self, row: int, column: str) -> int: ...
    def get_cell_height(self, row: int, column: str) -> int: ...
    def get_cell_hotspot_type(self, row: int, column: str) -> str: ...
    def get_cell_icon(self, row: int, column: str) -> str: ...
    def get_cell_left(self, row: int, column: str) -> int: ...
    def get_cell_list_box_count(self, row: int, column: str) -> int: ...
    def get_cell_list_box_cur_index(self, row: int, column: str) -> str: ...
    def get_cell_max_length(self, row: int, column: str) -> int: ...
    def get_cell_state(self, row: int, column: str) -> str: ...
    def get_cell_tooltip(self, row: int, column: str) -> str: ...
    def get_cell_top(self, row: int, column: str) -> int: ...
    def get_cell_type(self, row: int, column: str) -> str: ...
    def get_cell_value(self, row: int, column: str) -> str: ...
    def get_cell_width(self, row: int, column: str) -> int: ...
    def get_color_info(self, color: int) -> str: ...
    def get_column_data_type(self, column: str) -> str: ...
    def get_column_operation_type(self, column: str) -> str: ...
    def get_column_position(self, column: str) -> int: ...
    def get_column_sort_type(self, column: str) -> str: ...
    def get_column_titles(self, column: str) -> Any: ...
    def get_column_tooltip(self, column: str) -> str: ...
    def get_column_total_type(self, column: str) -> str: ...
    def get_displayed_column_title(self, column: str) -> str: ...
    def get_row_total_level(self, row: int) -> int: ...
    def get_symbol_info(self, symbol: str) -> str: ...
    def get_toolbar_button_checked(self, button_pos: int) -> bool: ...
    def get_toolbar_button_enabled(self, button_pos: int) -> bool: ...
    def get_toolbar_button_icon(self, button_pos: int) -> str: ...
    def get_toolbar_button_id(self, button_pos: int) -> str: ...
    def get_toolbar_button_text(self, button_pos: int) -> str: ...
    def get_toolbar_button_tooltip(self, button_pos: int) -> str: ...
    def get_toolbar_button_type(self, button_pos: int) -> str: ...
    def get_toolbar_focus_button(self) -> int: ...
    def has_cell_f4_help(self, row: int, column: str) -> bool: ...
    def history_cur_entry(self, row: int, column: str) -> str: ...
    def history_cur_index(self, row: int, column: str) -> int: ...
    def history_is_active(self, row: int, column: str) -> bool: ...
    def history_list(self, row: int, column: str) -> Any: ...
    def insert_rows(self, rows: str) -> None: ...
    def is_cell_hotspot(self, row: int, column: str) -> bool: ...
    def is_cell_symbol(self, row: int, column: str) -> bool: ...
    def is_cell_total_expander(self, row: int, column: str) -> bool: ...
    def is_column_filtered(self, column: str) -> bool: ...
    def is_column_key(self, column: str) -> bool: ...
    def is_total_row_expanded(self, row: int) -> bool: ...
    def modify_cell(self, row: int, column: str, value: str) -> None: ...
    def modify_check_box(self, row: int, column: str, checked: bool) -> None: ...
    def move_rows(self, from_row: int, to_row: int, dest_row: int) -> None: ...
    def press_button(self, row: int, column: str) -> None: ...
    def press_button_current_cell(self) -> None: ...
    def press_column_header(self, column: str) -> None: ...
    def press_enter(self) -> None: ...
    def press_f1(self) -> None: ...
    def press_f4(self) -> None: ...
    def press_toolbar_button(self, id: str) -> None: ...
    def press_toolbar_context_button(self, id: str) -> None: ...
    def press_total_row(self, row: int, column: str) -> None: ...
    def press_total_row_current_cell(self) -> None: ...
    def select_all(self) -> None: ...
    def select_column(self, column: str) -> None: ...
    def selection_changed(self) -> None: ...
    def select_toolbar_menu_item(self, id: str) -> None: ...
    def set_column_width(self, column: str, width: int) -> None: ...
    def set_current_cell(self, row: int, column: str) -> None: ...
    def trigger_modified(self) -> None: ...
    def by_val(self) -> None: ...
