# -*- coding: utf-8 -*-
# GENERADO automáticamente por pysap.codegen desde el PDF de la API.
# NO EDITAR A MANO: los cambios se perderán al regenerar.

from pysap.objects.base import GuiComponent


class GuiStatusbar(GuiComponent):
    @property
    def handle(self) -> int: ...
    @property
    def message_as_popup(self) -> bool: ...
    @property
    def message_has_long_text(self) -> int: ...
    @property
    def message_id(self) -> str: ...
    @property
    def message_number(self) -> str: ...
    @property
    def message_parameter(self) -> str: ...
    @property
    def message_type(self) -> str: ...
    def create_support_message_click(self) -> None: ...
    def double_click(self) -> None: ...
    def service_request_click(self) -> None: ...
