# -*- coding: utf-8 -*-
# GENERADO automáticamente por pysap.codegen desde el PDF de la API.
# NO EDITAR A MANO: los cambios se perderán al regenerar.

from typing import Any
from pysap.objects.base import GuiComponent


class GuiRadioButton(GuiComponent):
    @property
    def char_height(self) -> int: ...
    @property
    def char_left(self) -> int: ...
    @property
    def char_top(self) -> int: ...
    @property
    def char_width(self) -> int: ...
    @property
    def flushing(self) -> bool: ...
    @property
    def group_count(self) -> int: ...
    @property
    def group_members(self) -> Any: ...
    @property
    def group_pos(self) -> int: ...
    @property
    def is_left_label(self) -> bool: ...
    @property
    def is_right_label(self) -> bool: ...
    @property
    def left_label(self) -> Any: ...
    @property
    def right_label(self) -> Any: ...
    @property
    def selected(self) -> bool: ...
    @selected.setter
    def selected(self, value: bool) -> None: ...
    def select(self) -> None: ...
