# -*- coding: utf-8 -*-
# GENERADO automáticamente por pysap.codegen desde el PDF de la API.
# NO EDITAR A MANO: los cambios se perderán al regenerar.

from typing import Any
from pysap.objects.base import GuiComponent


class GuiConnection(GuiComponent):
    @property
    def children(self) -> Any: ...
    @property
    def connection_string(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def disabled_by_server(self) -> bool: ...
    @property
    def sessions(self) -> Any: ...
    def close_connection(self) -> None: ...
    def close_session(self, id: str) -> None: ...
