# -*- coding: utf-8 -*-
# GENERADO automáticamente por pysap.codegen desde el PDF de la API.
# NO EDITAR A MANO: los cambios se perderán al regenerar.

from typing import Any
from pysap.objects.base import GuiComponent


class GuiApplication(GuiComponent):
    @property
    def active_session(self) -> Any: ...
    @property
    def allow_system_messages(self) -> bool: ...
    @allow_system_messages.setter
    def allow_system_messages(self, value: bool) -> None: ...
    @property
    def buttonbar_visible(self) -> bool: ...
    @buttonbar_visible.setter
    def buttonbar_visible(self, value: bool) -> None: ...
    @property
    def children(self) -> Any: ...
    @property
    def connection_error_text(self) -> str: ...
    @property
    def connections(self) -> Any: ...
    @property
    def history_enabled(self) -> bool: ...
    @history_enabled.setter
    def history_enabled(self, value: bool) -> None: ...
    @property
    def major_version(self) -> int: ...
    @property
    def minor_version(self) -> int: ...
    @property
    def new_visual_design(self) -> bool: ...
    @property
    def patchlevel(self) -> int: ...
    @property
    def revision(self) -> int: ...
    @property
    def statusbar_visible(self) -> bool: ...
    @statusbar_visible.setter
    def statusbar_visible(self, value: bool) -> None: ...
    @property
    def titlebar_visible(self) -> bool: ...
    @titlebar_visible.setter
    def titlebar_visible(self, value: bool) -> None: ...
    @property
    def toolbar_visible(self) -> bool: ...
    @toolbar_visible.setter
    def toolbar_visible(self, value: bool) -> None: ...
    @property
    def utils(self) -> Any: ...
    def add_history_entry(self, fieldname: str, value: str) -> bool: ...
    def create_gui_collection(self) -> Any: ...
    def drop_history(self) -> bool: ...
    def ignore(self, window_handle: int) -> None: ...
    def open_connection(self, description: str, sync: Any, raise_: Any) -> Any: ...
    def open_connection_by_connection_string(self, connect_string: str, sync: Any, raise_: Any) -> Any: ...
    def register_rot(self) -> bool: ...
    def revoke_rot(self) -> None: ...
    def as_(self) -> None: ...
    def optional(self) -> None: ...
