# -*- coding: utf-8 -*-
# GENERADO automáticamente por pysap.codegen desde el PDF de la API.
# NO EDITAR A MANO: los cambios se perderán al regenerar.

from typing import Any
from pysap.objects.base import GuiComponent


class GuiSession(GuiComponent):
    @property
    def acc_enhanced_tab_chain(self) -> bool: ...
    @acc_enhanced_tab_chain.setter
    def acc_enhanced_tab_chain(self, value: bool) -> None: ...
    @property
    def acc_symbol_replacement(self) -> bool: ...
    @acc_symbol_replacement.setter
    def acc_symbol_replacement(self, value: bool) -> None: ...
    @property
    def active_window(self) -> Any: ...
    @property
    def busy(self) -> bool: ...
    @busy.setter
    def busy(self, value: bool) -> None: ...
    @property
    def error_list(self) -> Any: ...
    @error_list.setter
    def error_list(self, value: Any) -> None: ...
    @property
    def info(self) -> Any: ...
    @property
    def is_active(self) -> bool: ...
    @is_active.setter
    def is_active(self, value: bool) -> None: ...
    @property
    def is_list_box_active(self) -> bool: ...
    @property
    def list_box_curr_entry(self) -> int: ...
    @property
    def list_box_curr_entry_height(self) -> int: ...
    @property
    def list_box_curr_entry_left(self) -> int: ...
    @property
    def list_box_curr_entry_top(self) -> int: ...
    @property
    def list_box_curr_entry_width(self) -> int: ...
    @property
    def list_box_height(self) -> int: ...
    @property
    def list_box_left(self) -> int: ...
    @property
    def list_box_top(self) -> int: ...
    @property
    def list_box_width(self) -> int: ...
    @property
    def passport_pre_system_id(self) -> str: ...
    @passport_pre_system_id.setter
    def passport_pre_system_id(self, value: str) -> None: ...
    @property
    def passport_system_id(self) -> str: ...
    @passport_system_id.setter
    def passport_system_id(self, value: str) -> None: ...
    @property
    def passport_transaction_id(self) -> str: ...
    @passport_transaction_id.setter
    def passport_transaction_id(self, value: str) -> None: ...
    @property
    def progress_percent(self) -> Any: ...
    @property
    def progress_text(self) -> str: ...
    @property
    def record(self) -> bool: ...
    @record.setter
    def record(self, value: bool) -> None: ...
    @property
    def record_file(self) -> str: ...
    @record_file.setter
    def record_file(self, value: str) -> None: ...
    @property
    def save_as_unicode(self) -> bool: ...
    @save_as_unicode.setter
    def save_as_unicode(self, value: bool) -> None: ...
    @property
    def show_dropdown_keys(self) -> bool: ...
    @show_dropdown_keys.setter
    def show_dropdown_keys(self, value: bool) -> None: ...
    @property
    def suppress_backend_popups(self) -> bool: ...
    @suppress_backend_popups.setter
    def suppress_backend_popups(self, value: bool) -> None: ...
    @property
    def test_tool_mode(self) -> int: ...
    @test_tool_mode.setter
    def test_tool_mode(self, value: int) -> None: ...
    def as_std_number_format(self, number: str) -> str: ...
    def clear_error_list(self) -> None: ...
    def create_session(self) -> None: ...
    def enable_jaws_events(self) -> None: ...
    def end_transaction(self) -> None: ...
    def find_by_position(self, x: int, y: int, raise_: Any) -> Any: ...
    def get_icon_resource_name(self, text: str) -> str: ...
    def get_object_tree(self, id: str, props: Any) -> str: ...
    def get_v_key_description(self, v_key: int) -> str: ...
    def lock_session_ui(self) -> None: ...
    def send_command(self, command: str) -> None: ...
    def send_command_async(self, command: str) -> None: ...
    def start_transaction(self, transaction: str) -> None: ...
    def unlock_session_ui(self) -> None: ...
    def optional(self) -> None: ...
    def sample(self) -> None: ...
    def re_dim(self) -> None: ...
    def end(self) -> None: ...
    def with_(self) -> None: ...
    def by_val(self) -> None: ...
