# -*- coding: utf-8 -*-
# GENERADO automáticamente por pysap.codegen desde el PDF de la API.
# NO EDITAR A MANO: los cambios se perderán al regenerar.

from typing import Any
from pysap.objects.base import GuiComponent


class GuiTree(GuiComponent):
    @property
    def column_order(self) -> Any: ...
    @column_order.setter
    def column_order(self, value: Any) -> None: ...
    @property
    def hierarchy_header_width(self) -> int: ...
    @hierarchy_header_width.setter
    def hierarchy_header_width(self, value: int) -> None: ...
    @property
    def selected_node(self) -> str: ...
    @selected_node.setter
    def selected_node(self, value: str) -> None: ...
    @property
    def top_node(self) -> str: ...
    @top_node.setter
    def top_node(self, value: str) -> None: ...
    def change_checkbox(self, node_key: str, item_name: str, checked: bool) -> None: ...
    def click_link(self, node_key: str, item_name: str) -> None: ...
    def collapse_node(self, node_key: str) -> None: ...
    def default_context_menu(self) -> None: ...
    def double_click_item(self, node_key: str, item_name: str) -> None: ...
    def double_click_node(self, node_key: str) -> None: ...
    def ensure_visible_horizontal_item(self, node_key: str, item_name: str) -> None: ...
    def expand_node(self, node_key: str) -> None: ...
    def find_node_key_by_path(self, path: str) -> str: ...
    def get_abap_image(self, key: str, name: str) -> str: ...
    def get_all_node_keys(self) -> Any: ...
    def get_check_box_state(self, node_key: str, item_name: str) -> bool: ...
    def get_column_col(self, col_name: str) -> Any: ...
    def get_column_headers(self) -> Any: ...
    def get_column_index_from_name(self, key: str) -> int: ...
    def get_column_names(self) -> Any: ...
    def get_column_title_from_name(self, key: str) -> str: ...
    def get_column_titles(self) -> Any: ...
    def get_focused_node_key(self) -> str: ...
    def get_hierarchy_level(self, key: str) -> int: ...
    def get_hierarchy_title(self) -> str: ...
    def get_is_disabled(self, node_key: str, item_name: str) -> bool: ...
    def get_is_editable(self, node_key: str, item_name: str) -> bool: ...
    def get_is_high_lighted(self, node_key: str, item_name: str) -> bool: ...
    def get_item_height(self, node_key: str, item_name: str) -> int: ...
    def get_item_left(self, node_key: str, item_name: str) -> int: ...
    def get_item_style(self, node_key: str, item_name: str) -> int: ...
    def get_item_text(self, key: str, name: str) -> str: ...
    def get_item_text_color(self, key: str, name: str) -> Any: ...
    def get_item_tool_tip(self, key: str, name: str) -> str: ...
    def get_item_top(self, node_key: str, item_name: str) -> int: ...
    def get_item_type(self, key: str, name: str) -> int: ...
    def get_item_width(self, node_key: str, item_name: str) -> int: ...
    def get_list_tree_node_item_count(self, node_key: str) -> int: ...
    def get_next_node_key(self, node_key: str) -> str: ...
    def get_node_abap_image(self, key: str) -> str: ...
    def get_node_children_count(self, key: str) -> int: ...
    def get_node_children_count_by_path(self, path: str) -> int: ...
    def get_node_height(self, key: str) -> int: ...
    def get_node_index(self, key: str) -> int: ...
    def get_node_item_headers(self, node_key: str) -> Any: ...
    def get_node_key_by_path(self, path: str) -> str: ...
    def get_node_left(self, key: str) -> int: ...
    def get_node_path_by_key(self, key: str) -> str: ...
    def get_nodes_col(self) -> Any: ...
    def get_node_style(self, node_key: str) -> int: ...
    def get_node_text_by_key(self, path: str) -> str: ...
    def get_node_text_by_path(self, path: str) -> str: ...
    def get_node_text_color(self, key: str) -> Any: ...
    def get_node_tool_tip(self, node_key: str) -> str: ...
    def get_node_top(self, key: str) -> int: ...
    def get_node_width(self, key: str) -> int: ...
    def get_parent(self, c_key: str) -> str: ...
    def get_previous_node_key(self, node_key: str) -> str: ...
    def get_selected_nodes(self) -> Any: ...
    def get_selection_mode(self) -> int: ...
    def get_style_description(self, n_style: int) -> str: ...
    def get_sub_nodes_col(self, node_key: str) -> Any: ...
    def get_tree_type(self) -> int: ...
    def header_context_menu(self, header_name: str) -> None: ...
    def is_folder(self, node_key: str) -> bool: ...
    def is_folder_expandable(self, node_key: str) -> bool: ...
    def is_folder_expanded(self, node_key: str) -> bool: ...
    def item_context_menu(self, node_key: str, item_name: str) -> None: ...
    def node_context_menu(self, node_key: str) -> None: ...
    def press_button(self, node_key: str, item_name: str) -> None: ...
    def press_header(self, header_name: str) -> None: ...
    def press_key(self, key: str) -> None: ...
    def select_column(self, column_name: str) -> None: ...
    def selected_item_column(self) -> str: ...
    def selected_item_node(self) -> str: ...
    def select_item(self, node_key: str, item_name: str) -> None: ...
    def select_node(self, node_key: str) -> None: ...
    def set_check_box_state(self, node_key: str, item_name: str, state: int) -> None: ...
    def set_column_width(self, column_name: str, width: int) -> None: ...
    def unselect_all(self) -> None: ...
    def unselect_column(self, column_name: str) -> None: ...
    def unselect_node(self, node_key: str) -> None: ...
    def by_val(self) -> None: ...
    def as_(self) -> None: ...
    def return_(self) -> None: ...
