# -*- coding: utf-8 -*-
# GENERADO automáticamente por pysap.codegen desde el PDF de la API.
# NO EDITAR A MANO: los cambios se perderán al regenerar.

from typing import Any
from pysap.objects.base import GuiComponent


class GuiCheckBox(GuiComponent):
    @property
    def color_index(self) -> int: ...
    @property
    def color_intensified(self) -> bool: ...
    @property
    def color_inverse(self) -> bool: ...
    @property
    def flushing(self) -> bool: ...
    @property
    def is_left_label(self) -> bool: ...
    @property
    def is_list_element(self) -> bool: ...
    @property
    def is_right_label(self) -> bool: ...
    @property
    def left_label(self) -> Any: ...
    @property
    def right_label(self) -> Any: ...
    @property
    def row_text(self) -> str: ...
    @property
    def selected(self) -> bool: ...
    @selected.setter
    def selected(self, value: bool) -> None: ...
    @property
    def count(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def new_enum(self) -> Any: ...
    @property
    def type_(self) -> str: ...
    @property
    def type_as_number(self) -> int: ...
    def get_list_property(self, property: str) -> str: ...
    def get_list_property_non_rec(self, property: str) -> str: ...
